# Generated by Django 5.0.3 on 2024-03-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Web", "0002_prettynum_alter_userinfo_depart_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
    ]
